server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes - must come before default filters
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: StripPrefix
              args:
                parts: 0

        # Polls Service Routes
        - id: polls-service
          uri: http://polls-service:8082
          predicates:
            - Path=/api/polls/**
          filters:
            - name: StripPrefix
              args:
                parts: 0

        # Voting Service Routes
        - id: voting-service
          uri: http://voting-service:8083
          predicates:
            - Path=/votes/**
          filters:
            - name: StripPrefix
              args:
                parts: 0

        # Results Service Routes
        - id: results-service
          uri: http://results-service:8084
          predicates:
            - Path=/api/results/**
          filters:
            - name: StripPrefix
              args:
                parts: 0

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

  tracing:
    sampling:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_ENDPOINT:http://localhost:6334/api/v2/spans}

gateway:
  jwt:
    # Secure 256-bit (32-byte) base64-encoded secret for JWT signing
    # MUST match the auth-service secret for token validation
    # This is a 32-byte string "RunRtSecureJWTSigningKey2025!!" encoded in base64
    base64secret: ${GATEWAY_JWT_BASE64SECRET:UnVuUnRTZWN1cmVKV1RTaWduaW5nS2V5MjAyNSEhISEhISEhISEhISEhISEhISE=}
    expirationms: ${GATEWAY_JWT_EXPIRATIONMS:86400000}
